/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'ag-green': '#4ade80',
        'ag-dark': '#ffffff',
        'ag-card': '#f8fafc',
        'ag-card2': '#f1f5f9',
        "on-surface": "#191c1c",
        "inverse-on-surface": "#eff1f0",
        "primary-container": "#6fb10d",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#344e00",
        "on-tertiary-container": "#283d00",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#102000",
        "surface-container": "#eceeed",
        "on-secondary-container": "#003e68",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#a5d64f",
        "secondary-fixed": "#d0e4ff",
        "surface-container-high": "#e6e9e8",
        "primary-fixed": "#aff757",
        "inverse-surface": "#2e3131",
        "tertiary-fixed": "#c0f368",
        "error-container": "#ffdad6",
        "primary": "#3f6900",
        "on-primary-container": "#233d00",
        "secondary-container": "#51abfd",
        "on-secondary-fixed-variant": "#00497b",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "tertiary": "#476800",
        "tertiary-container": "#7fae2a",
        "surface-bright": "#f8faf9",
        "secondary": "#0062a1",
        "on-background": "#191c1c",
        "inverse-primary": "#94da3d",
        "surface-dim": "#d8dad9",
        "surface": "#f8faf9",
        "on-primary-fixed-variant": "#2e4f00",
        "on-tertiary-fixed": "#131f00",
        "outline-variant": "#c1cab2",
        "primary-fixed-dim": "#94da3d",
        "on-secondary-fixed": "#001d35",
        "surface-container-low": "#f2f4f3",
        "on-error-container": "#93000a",
        "surface-variant": "#e1e3e2",
        "background": "#f8faf9",
        "outline": "#727a65",
        "surface-tint": "#3f6900",
        "surface-container-highest": "#e1e3e2",
        "on-surface-variant": "#424937",
        "secondary-fixed-dim": "#9ccaff"
      },
      fontFamily: {
        display: ['Outfit', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"]
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [],
};
