/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        /* === Farmer-Centric Palette === */
        'kisan-green': '#2D6A4F',
        'kisan-green-light': '#40916C',
        'kisan-green-dark': '#1B4332',
        'harvest-gold': '#FFB703',
        'harvest-gold-light': '#FFC933',
        'harvest-gold-dark': '#E09F00',
        'earth-brown': '#4E342E',
        'earth-brown-light': '#6D4C41',
        'earth-brown-dark': '#3E2723',
        'field-green': '#52B788',
        'field-green-light': '#74C69D',
        'cream': '#FFF8E7',
        'cream-dark': '#FFF0CC',
        'warm-white': '#FEFCF3',
        'pure-black': '#000000',
        'text-primary': '#1A1A1A',
        'text-secondary': '#3D3D3D',
        'text-muted': '#5C5C5C',
        'whatsapp': '#25D366',
        'whatsapp-dark': '#128C7E',
        /* === Legacy compat (for any missed refs) === */
        'ag-green': '#2D6A4F',
        'primary': '#2D6A4F',
        'primary-container': '#40916C',
        'on-primary': '#ffffff',
        'surface': '#FFF8E7',
        'on-surface': '#1A1A1A',
        'on-surface-variant': '#3D3D3D',
        'surface-container': '#FFF0CC',
        'surface-container-low': '#FEFCF3',
        'surface-variant': '#F5EDDB',
        'outline-variant': '#D4C9A8',
        'secondary': '#4E342E',
        'secondary-container': '#6D4C41',
        'on-secondary': '#ffffff',
        'tertiary': '#FFB703',
        'tertiary-container': '#FFC933',
      },
      fontFamily: {
        display: ['Outfit', 'sans-serif'],
        headline: ['Poppins', 'Outfit', 'sans-serif'],
        body: ['Poppins', 'Inter', 'sans-serif'],
        label: ['Poppins', 'Inter', 'sans-serif'],
        devanagari: ['Tiro Devanagari Marathi', 'Poppins', 'sans-serif'],
      },
      borderRadius: {
        'kisan': '20px',
        'kisan-lg': '28px',
        'kisan-xl': '36px',
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'fade-in-up': 'fadeInUp 0.6s ease-out',
        'whatsapp-pulse': 'whatsappPulse 2s ease-in-out infinite',
        'whatsapp-vibrate': 'whatsappVibrate 0.3s ease-in-out infinite',
        'float': 'float 3s ease-in-out infinite',
        'slide-up': 'slideUp 0.5s ease-out',
        'badge-shine': 'badgeShine 3s ease-in-out infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(30px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        whatsappPulse: {
          '0%, 100%': { transform: 'scale(1)', boxShadow: '0 0 0 0 rgba(37, 211, 102, 0.5)' },
          '50%': { transform: 'scale(1.05)', boxShadow: '0 0 0 15px rgba(37, 211, 102, 0)' },
        },
        whatsappVibrate: {
          '0%, 100%': { transform: 'rotate(0deg)' },
          '25%': { transform: 'rotate(5deg)' },
          '75%': { transform: 'rotate(-5deg)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        badgeShine: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
      },
      boxShadow: {
        '3d': '0 4px 0 0 #1B4332, 0 6px 20px rgba(45, 106, 79, 0.3)',
        '3d-gold': '0 4px 0 0 #E09F00, 0 6px 20px rgba(255, 183, 3, 0.3)',
        '3d-hover': '0 2px 0 0 #1B4332, 0 4px 15px rgba(45, 106, 79, 0.3)',
        'kisan': '0 4px 20px rgba(45, 106, 79, 0.15)',
        'kisan-lg': '0 8px 40px rgba(45, 106, 79, 0.2)',
        'warm': '0 4px 20px rgba(78, 52, 46, 0.1)',
      },
    },
  },
  plugins: [],
};
