export const products = [
  {
    id: 1,
    name: 'Organic Turmeric Powder',
    category: 'Spice Collection',
    description: 'High-curcumin certified organic turmeric, cold-ground for maximum potency.',
    fullDescription: 'Our Organic Turmeric Powder is sourced from the finest farms where traditional cultivation methods are preserved. With a high curcumin content of at least 5%, our turmeric is cold-ground to ensure that the natural oils and beneficial properties are retained. It is perfect for both culinary and medicinal use, offering a vibrant color and pungent aroma that is characteristic of premium quality turmeric.',
    price: '₹ 340 / kg',
    image: 'https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=500&q=80',
    specifications: [
      'Moisture: max 10%',
      'Curcumin Content: >5%',
      'Ash: max 6%',
      'Starch: 0%',
      'Origin: South India',
    ],
  },
  {
    id: 2,
    name: 'Cold-Pressed Coconut Oil',
    category: 'Food Products',
    description: 'Virgin coconut oil extracted using traditional wood-pressed method.',
    fullDescription: 'Agri-Gen\'s Cold-Pressed Coconut Oil is extracted from sun-dried coconut copras using the traditional Chekku (Wood Pressed) method. This process ensures that the oil retains its natural flavor, vitamins, and minerals. It is rich in lauric acid and medium-chain triglycerides, making it an excellent choice for cooking, hair care, and skin health.',
    price: '₹ 560 / L',
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=500&q=80',
    specifications: [
      'FFA: max 0.5%',
      'Moisture: max 0.1%',
      'Iodine Value: 7-10',
      'Peroxide Value: 0',
      'Extraction: Wood Pressed',
    ],
  },
  {
    id: 3,
    name: 'Ashwagandha Root Extract',
    category: 'Nutraceuticals',
    description: 'Standardized Withania somnifera extract with 5% withanolides for stress relief.',
    fullDescription: 'Our Ashwagandha Root Extract (Withania somnifera) is standardized to contain a minimum of 5% withanolides. Produced using a green extraction process, it provides a full-spectrum extract that captures the synergy of the plant\'s active components. It is widely recognized for its adaptogenic properties, helping the body manage stress and improve overall well-being.',
    price: '₹ 800 / kg',
    image: 'https://images.unsplash.com/photo-1600857062241-98e5dba7f74e?w=500&q=80',
    specifications: [
      'Withanolides (HPLC): >5%',
      'Solubility: Water Soluble',
      'Heavy Metals: Within EU limits',
      'Particle Size: 100% through 80 mesh',
      'Shelf Life: 24 months',
    ],
  },
  {
    id: 4,
    name: 'Organic Moringa Powder',
    category: 'Green Formulation',
    description: 'Sun-dried and milled Moringa oleifera leaves — rich in 92 nutrients.',
    fullDescription: 'Moringa oleifera, often referred to as the "Miracle Tree," provides leaves that are nutritional powerhouses. Our powder is created by sun-drying the leaves at controlled temperatures and milling them into an ultra-fine powder. It is an exceptional source of vitamins, minerals, and all 9 essential amino acids.',
    price: '₹ 450 / kg',
    image: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=500&q=80',
    specifications: [
      'Moisture: max 8%',
      'Protein: ~25%',
      'Fiber: ~12%',
      'Mesh size: 80-100',
      'Certifications: Organic, Kosher',
    ],
  },
  {
    id: 5,
    name: 'Premium Basmati Rice',
    category: 'Agro-commodities',
    description: 'Naturally aged long-grain basmati from the foothills of the Himalayas.',
    fullDescription: 'Grown in the fertile soil of the Himalayan foothills and nurtured by pure glacier water, our Premium Basmati Rice is naturally aged for at least 12-18 months. This aging process enhances its aroma and ensures that the grains stay separate and fluffy after cooking. Known for its extra-long grains and exquisite nutty flavor.',
    price: '₹ 220 / kg',
    image: 'https://images.unsplash.com/photo-1536304929831-ee1ca9d44906?w=500&q=80',
    specifications: [
      'Average Grain Length: 8.3mm+',
      'Purity: 95%',
      'Moisture: 12.5%',
      'Broken: max 1%',
      'Admixture: max 5%',
    ],
  },
  {
    id: 6,
    name: 'Black Pepper Whole',
    category: 'Spice Collection',
    description: 'Bold, aromatic whole black pepper with naturally high piperine content.',
    fullDescription: 'Our Black Pepper (Piper nigrum) is sourced from the Malabar coast, famous for producing the world\'s most aromatic pepper. These bold grains are hand-sorted and sun-dried to maintain their essential oils and high piperine content, which provides that characteristic sharp heat and complex flavor profile.',
    price: '₹ 680 / kg',
    image: 'https://images.unsplash.com/photo-1612690669207-fed642192c40?w=500&q=80',
    specifications: [
      'Grade: Bold (5mm+)',
      'Piperine: min 5%',
      'Moisture: max 12%',
      'Total Ash: max 7%',
      'Microbial: USP/EU compliant',
    ],
  },
  {
    id: 7,
    name: 'Neem Oil (Food Grade)',
    category: 'Green Formulation',
    description: '100% pure cold-pressed neem oil with high azadirachtin content.',
    fullDescription: 'Agri-Gen\'s Neem Oil is cold-pressed from the highest quality neem seeds. It is 100% pure and natural, containing no additives. Rich in azadirachtin, it is highly effective in organic farming as a natural pesticide and soil conditioner, as well as in personal care formulations for its anti-bacterial and anti-fungal properties.',
    price: '₹ 380 / L',
    image: 'https://images.unsplash.com/photo-1598454444604-5bf1af21f8e9?w=500&q=80',
    specifications: [
      'Azadirachtin: >1500 ppm',
      'FFA: max 5%',
      'Moisture: max 0.2%',
      'Extraction: Cold Pressed',
      'Refractive Index: 1.46-1.47',
    ],
  },
  {
    id: 8,
    name: 'Raw Organic Honey',
    category: 'Food Products',
    description: 'Wild-harvested multifloral honey, unheated, unfiltered, and raw.',
    fullDescription: 'Our Raw Organic Honey is harvested from deep forest regions, where bees forage on a variety of wild blossoms. Unlike commercial honey, ours is never heated or micro-filtered, preserving the natural enzymes, pollen, and antioxidants. It is truly nature\'s gold in its most honest form.',
    price: '₹ 900 / kg',
    image: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=500&q=80',
    specifications: [
      'Fructose/Glucose Ratio: >1.0',
      'Moisture: max 18%',
      'HMF: <40 mg/kg',
      'Pollen Count: High',
      'Diastase Activity: >8 (Schade scale)',
    ],
  },
  {
    id: 9,
    name: 'Organic Sesame Seeds',
    category: 'Agro-commodities',
    description: 'Hulled and unhulled sesame seeds from organically managed farms.',
    fullDescription: 'Sourced from farms practicing sustainable agriculture, our Organic Sesame Seeds are rich in oil, protein, and minerals. We offer both hulled and unhulled varieties, processed in a hygienic environment to ensure purity. They are ideal for oil extraction, bakery products, and traditional confectionery.',
    price: '₹ 190 / kg',
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=500&q=80',
    specifications: [
      'Purity: 99.95%',
      'Oil Content: min 48%',
      'Moisture: max 6%',
      'Admixture: max 0.05%',
      'Damaged Grains: max 0.5%',
    ],
  },
  {
    id: 10,
    name: 'Triphala Extract',
    category: 'Nutraceuticals',
    description: 'Classical Ayurvedic formulation of three fruits for digestive health.',
    fullDescription: 'Triphala is a legendary Ayurvedic combination of Amla, Haritaki, and Bibhitaki. Our extract is prepared using a standardized ratio of these fruits to maximize their synergistic effect on digestion and detoxification. It is standardized for tannins to ensure consistent therapeutic efficacy.',
    price: '₹ 650 / kg',
    image: 'https://images.unsplash.com/photo-1567593810070-7a3d471af022?w=500&q=80',
    specifications: [
      'Standardized: 30-40% Tannins',
      'Extract Ratio: 10:1',
      'Appearance: Brown Powder',
      'Heavy Metals: Within safe limits',
      'Microbiology: USP compliant',
    ],
  },
  {
    id: 11,
    name: 'Cardamom Green Pods',
    category: 'Spice Collection',
    description: 'Premium green cardamom with superior aroma, sourced from Kerala highlands.',
    fullDescription: 'Often called the "Queen of Spices," our Green Cardamom is sourced from the lush hills of Idukki, Kerala. We hand-pick only the bold, deep green pods that are fully matured. These are slowly dried to preserve the essential oils, resulting in an unbeatable aroma and flavor that defines gourmet quality.',
    price: '₹ 1,800 / kg',
    image: 'https://images.unsplash.com/photo-1599060054100-9df79b3d2870?w=500&q=80',
    specifications: [
      'Size: 7mm / 8mm Bold',
      'Color: Natural Green',
      'Moisture: 10-12%',
      'Volatile Oil: min 6%',
      'Empty Pods: max 1%',
    ],
  },
  {
    id: 12,
    name: 'Organic Wheat Flour',
    category: 'Food Products',
    description: 'Stone-milled whole wheat flour from certified organic wheat farms.',
    fullDescription: 'Our Organic Wheat Flour (Chakki Atta) is produced from premium organic wheat grown in Central India. It is stone-milled to maintain the bran and germ, ensuring that all dietary fibers and nutrients are preserved. No additives, bleaching agents, or preservatives are used, making it pure and healthy.',
    price: '₹ 75 / kg',
    image: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=500&q=80',
    specifications: [
      'Protein: min 11.5%',
      'Gluten: min 9%',
      'Ash: 1.3-1.6%',
      'Moisture: max 12%',
      'Milling: Stone Ground (Chakki)',
    ],
  },
];
